import { PILOT_BID_LIMIT, PILOT_JOB_LIMIT } from './pilot';

// Owner-provided support contact. Not an invented legal operator or DPO.
export const SUPPORT_TELEGRAM = { label: '@kentukaa', href: 'https://t.me/kentukaa' };
export const LEGAL_DRAFT = {
  ru: 'Черновик для бесплатного пилота в Бельцах. Сведения об операторе, основания обработки и сроки хранения ещё не утверждены. Документ не является окончательной политикой.',
  ro: 'Proiect pentru pilotul gratuit din Bălți. Identitatea operatorului, temeiurile prelucrării și perioadele de păstrare nu sunt încă aprobate. Documentul nu reprezintă politica finală.',
};

export function privacySections(locale: string) {
  return locale === 'ru' ? [
    { title: '1. Данные аккаунта и работы', text: 'Для входа используется номер телефона и SMS-код. В анкете — имя, город и выбранная роль. Профиль мастера может содержать категории, описание, опыт, районы, фото работ и контакты для связи. Сохраняются заявки, отклики, выбор исполнителя, отзывы и уведомления.' },
    { title: '2. Публичная информация и закрытые контакты', text: 'Имя, описание и фото профиля мастера, категории, рейтинг и отзывы видны в каталоге. Описание заявки, бюджет, район и фото могут быть доступны посетителям. Телефон и мессенджеры не входят в публичный каталог; контакты для работы открываются участникам после выбора исполнителя. Не включайте адрес, телефон или чужие личные данные в публичные тексты и фотографии.' },
    { title: '3. Карта и GPS', text: 'Для заявки нужна точка на карте в зоне пилота Бельц. GPS запрашивается только по кнопке; можно выбрать место вручную. Точная точка сохраняется для заявки и доступна заказчику и выбранному мастеру во время работы. Фоновое отслеживание не используется. Карта загружает тайлы OpenStreetMap: сервис карт получает технические данные запроса и область карты. Точка не отправляется в сервис обратного геокодирования.' },
    { title: '4. Фотографии', text: 'Новые загрузки JPG, PNG и WebP обрабатываются до публикации: исходные EXIF, GPS и другие метаданные не сохраняются в полученном JPEG. Видимые в кадре адреса, лица или документы при этом не скрываются. Фото профиля и заявки публичные. Ранее загруженные фотографии ещё требуют отдельной проверки. Удаление снимка из формы само по себе не удаляет файл из хранилища.' },
    { title: '5. Telegram', text: 'Подключение необязательно: одноразовая ссылка из профиля действует 10 минут. Для доставки сохраняется идентификатор чата; также обрабатываются команды боту и номера обновлений для защиты от повторов. Бот не читает личные разговоры с другими пользователями. Сообщения могут содержать описание заявки, категорию, город и ссылку. Отключение — команда /stop. Уведомления на сайте доступны без Telegram.' },
    { title: '6. Подрядчики и хранение', text: 'Supabase используется для аккаунтов, базы и файлов; Vercel — для сайта; SMS доставляет настроенный провайдер Twilio, Telegram — сообщения подключённому пользователю. География и условия обработки у каждого подрядчика, сроки хранения аккаунтов, фото, технических журналов и резервных копий подлежат подтверждению до открытия пилота. Автоматическое удаление всех данных по фиксированному сроку сейчас не заявлено.' },
    { title: '7. Cookie и запросы пользователя', text: 'Cookie авторизации позволяют сохранять вход между посещениями; выйти можно через меню аккаунта. Очистка cookie потребует нового входа. Имя и профиль редактируются в аккаунте. Запрос копии данных, удаления или отключения обработки можно направить в поддержку @kentukaa; удаление пока требует ручной обработки и проверки владельца аккаунта. Не отправляйте SMS-код или паспорт в поддержку. Процедура и сроки исполнения должны быть утверждены до публичного запуска.' },
  ] : [
    { title: '1. Datele contului și lucrărilor', text: 'Autentificarea folosește numărul de telefon și un cod SMS. Formularul conține numele, orașul și rolul ales. Profilul meșterului poate include categorii, descriere, experiență, zone, poze și contacte. Sunt păstrate cereri, oferte, selectarea executantului, recenzii și notificări.' },
    { title: '2. Informații publice și contacte private', text: 'Numele, descrierea și pozele profilului de meșter, categoriile, ratingul și recenziile sunt vizibile în catalog. Descrierea cererii, bugetul, zona și pozele pot fi accesibile vizitatorilor. Telefonul și contactele nu fac parte din catalogul public; contactele pentru lucrare se deschid participanților după alegerea executantului. Nu includeți adresa, telefonul sau datele personale ale altora în texte și poze publice.' },
    { title: '3. Hartă și GPS', text: 'Cererea necesită un punct pe hartă în zona pilotului din Bălți. GPS este solicitat numai prin buton; locul poate fi marcat manual. Punctul exact este păstrat pentru cerere și este disponibil clientului și meșterului selectat în timpul lucrării. Nu există urmărire în fundal. Harta încarcă dale OpenStreetMap: furnizorul primește date tehnice ale cererii și zona hărții. Punctul nu este trimis unui serviciu de geocodare inversă.' },
    { title: '4. Fotografii', text: 'Încărcările noi JPG, PNG și WebP sunt procesate înainte de publicare: metadatele originale EXIF, GPS și altele nu se păstrează în JPEG-ul rezultat. Adresele, fețele sau documentele vizibile în imagine nu sunt ascunse. Pozele profilului și cererii sunt publice. Fotografiile încărcate anterior necesită o verificare separată. Eliminarea unei poze din formular nu șterge automat fișierul din stocare.' },
    { title: '5. Telegram', text: 'Conectarea este opțională: linkul unic din profil este valabil 10 minute. Pentru livrare se păstrează identificatorul chatului; se procesează și comenzile către bot și numerele actualizărilor pentru protecție împotriva repetărilor. Botul nu citește conversațiile private cu alți utilizatori. Mesajele pot conține descrierea cererii, categoria, orașul și linkul. Deconectarea se face prin /stop. Notificările pe site sunt disponibile fără Telegram.' },
    { title: '6. Furnizori și păstrare', text: 'Supabase este utilizat pentru conturi, bază și fișiere; Vercel pentru site; furnizorul SMS configurat Twilio livrează codurile, iar Telegram mesajele utilizatorului conectat. Localizarea și condițiile prelucrării fiecărui furnizor, perioadele de păstrare a conturilor, pozelor, jurnalelor tehnice și copiilor de rezervă trebuie confirmate înainte de deschiderea pilotului. Nu declarăm ștergerea automată a tuturor datelor la un termen fix.' },
    { title: '7. Cookie și solicitări', text: 'Cookie-urile de autentificare păstrează sesiunea între vizite; ieșirea se face din meniul contului. Ștergerea cookie-urilor necesită o nouă autentificare. Numele și profilul se editează în cont. Puteți solicita o copie a datelor, ștergerea sau oprirea prelucrării prin suportul @kentukaa; ștergerea necesită încă procesare manuală și verificarea titularului contului. Nu trimiteți codul SMS sau pașaportul la suport. Procedura și termenele trebuie aprobate înainte de lansarea publică.' },
  ];
}

export function termsSections(locale: string) {
  return locale === 'ru' ? [
    { title: '1. Бесплатный пилот', text: 'MASTER Moldova помогает находить мастеров и ремонтные заявки в Бельцах на русском и румынском языках. Расширение географии не включено в текущий пилот.' },
    { title: '2. Аккаунт', text: 'Вход — по телефону и SMS. Указывайте достоверное имя и профиль. Один аккаунт может создавать заявки и принимать работу: роль меняется в профиле. Не передавайте доступ и SMS-коды другим людям.' },
    { title: '3. Заявки и отклики', text: `Публикация и отклики бесплатны; продажа и списание кредитов выключены. Для защиты от спама допускается до ${PILOT_JOB_LIMIT} новых заявок и ${PILOT_BID_LIMIT} новых откликов за скользящие 24 часа. Для заявки обязательны категория, описание и точка в зоне Бельц. Повтор отправки из той же открытой формы возвращает созданную заявку.` },
    { title: '4. Выбор и оплата работы', text: 'Заказчик выбирает отклик, после чего участники получают контакты для связи. Объём, цену, сроки и оплату самой работы стороны согласуют напрямую. Сайт не принимает оплату за работы и не хранит её как безопасную сделку. Завершение заявки и отзыв оформляются заказчиком на сайте.' },
    { title: '5. Фото и содержание', text: 'Размещайте только фотографии, которые вправе публиковать. Не публикуйте документы, телефоны, точные адреса или чужие личные данные в описаниях и фото. Запрещены ложные сведения, спам, угрозы и поддельные отзывы. Сообщить о нарушении можно поддержке со ссылкой на заявку или профиль.' },
    { title: '6. Отметка проверки', text: 'Отметка «Проверен» означает ручной просмотр профиля модератором. В пилоте не требуется паспорт. Отметка не подтверждает профессиональную квалификацию и не гарантирует качество, законность или сроки работы.' },
    { title: '7. Ошибки, жалобы и изменения', text: 'При ошибке или споре обратитесь в поддержку @kentukaa. Приложите ссылку и описание ситуации, без SMS-кодов и лишних личных данных. Проверка жалоб выполняется вручную; конкретный срок ответа пока не установлен. Условия платных функций, если они появятся, будут опубликованы отдельно до их включения.' },
  ] : [
    { title: '1. Pilot gratuit', text: 'MASTER Moldova ajută la găsirea meșterilor și a cererilor de reparații în Bălți, în rusă și română. Extinderea geografică nu este inclusă în pilotul actual.' },
    { title: '2. Cont', text: 'Autentificarea se face prin telefon și SMS. Indicați un nume și un profil corect. Același cont poate publica cereri și accepta lucrări: rolul se schimbă în profil. Nu transmiteți accesul sau codurile SMS altor persoane.' },
    { title: '3. Cereri și oferte', text: `Publicarea și ofertele sunt gratuite; vânzarea și deducerea creditelor sunt dezactivate. Pentru protecție împotriva spamului sunt permise până la ${PILOT_JOB_LIMIT} cereri noi și ${PILOT_BID_LIMIT} oferte noi în 24 de ore consecutive. Cererea necesită categorie, descriere și un punct în zona Bălți. Retrimiterea din același formular deschis returnează cererea creată.` },
    { title: '4. Alegerea și plata lucrării', text: 'Clientul selectează o ofertă, apoi participanții primesc contactele pentru comunicare. Volumul, prețul, termenele și plata lucrării se stabilesc direct între părți. Site-ul nu încasează plata lucrărilor și nu o păstrează într-un serviciu escrow. Finalizarea cererii și recenzia sunt înregistrate de client pe site.' },
    { title: '5. Poze și conținut', text: 'Publicați numai fotografii pe care aveți dreptul să le folosiți. Nu publicați documente, telefoane, adrese exacte sau datele personale ale altora în descrieri și poze. Sunt interzise informațiile false, spamul, amenințările și recenziile fabricate. Raportați încălcarea la suport cu linkul cererii sau profilului.' },
    { title: '6. Insigna de verificare', text: 'Insigna «Verificat» înseamnă că profilul a fost examinat manual de un moderator. Pilotul nu necesită pașaport. Insigna nu confirmă calificarea profesională și nu garantează calitatea, legalitatea sau termenele lucrării.' },
    { title: '7. Erori, reclamații și modificări', text: 'Pentru erori sau litigii contactați suportul @kentukaa. Includeți linkul și descrierea situației, fără coduri SMS sau date personale inutile. Reclamațiile sunt examinate manual; un termen exact de răspuns nu este încă stabilit. Condițiile funcțiilor plătite, dacă vor apărea, vor fi publicate separat înainte de activare.' },
  ];
}

export function supportFaqs(locale: string) {
  return locale === 'ru' ? [
    { q: 'Как стать мастером или заказчиком?', a: 'Войдите по телефону и SMS, укажите имя и роль. В профиле можно переключиться между мастером и заказчиком. Мастеру нужно выбрать хотя бы одну специализацию.' },
    { q: 'Не получаю SMS-код', a: 'Проверьте номер с кодом +373. Повторная отправка доступна через 60 секунд. Если код не приходит, напишите @kentukaa. Вход по e-mail не предусмотрен.' },
    { q: 'Как подключить Telegram?', a: 'В профиле, в разделе Telegram, создайте одноразовую ссылку и откройте бота. Нажмите Start в течение 10 минут. Для отключения отправьте /stop. Уведомления на сайте доступны и без бота.' },
    { q: 'Что означает «Проверен»?', a: 'Модератор вручную просмотрел профиль. Паспорт для пилота не требуется; отметка не гарантирует квалификацию или качество работ. Заявку на просмотр можно отправить из кабинета мастера.' },
    { q: 'Заявка не публикуется', a: `Выберите категорию, напишите минимум 20 символов и отметьте точку в зоне Бельц. Дождитесь загрузки фото. Лимит — ${PILOT_JOB_LIMIT} новых заявок за 24 часа. При потерянном ответе повторите отправку из этой формы. Если данные уже опубликованы, откройте показанную ссылку.` },
    { q: 'Как получить копию данных или удалить аккаунт?', a: 'Напишите @kentukaa с просьбой и ссылкой на свой профиль. Поддержка должна подтвердить владельца аккаунта; не отправляйте SMS-код или паспорт. Автоматическое удаление в кабинете пока недоступно.' },
  ] : [
    { q: 'Cum devin meșter sau client?', a: 'Autentificați-vă prin telefon și SMS, indicați numele și rolul. Puteți schimba rolul în profil. Meșterul trebuie să aleagă cel puțin o specializare.' },
    { q: 'Nu primesc codul SMS', a: 'Verificați numărul cu prefixul +373. Retrimiterea este disponibilă după 60 de secunde. Dacă nu primiți codul, scrieți la @kentukaa. Autentificarea prin e-mail nu este disponibilă.' },
    { q: 'Cum conectez Telegram?', a: 'În profil, în secțiunea Telegram, creați un link unic și deschideți botul. Apăsați Start în 10 minute. Pentru deconectare trimiteți /stop. Notificările pe site sunt disponibile și fără bot.' },
    { q: 'Ce înseamnă «Verificat»?', a: 'Un moderator a examinat manual profilul. Pilotul nu necesită pașaport; insigna nu garantează calificarea sau calitatea lucrării. Puteți solicita examinarea din panoul meșterului.' },
    { q: 'Cererea nu se publică', a: `Alegeți categoria, scrieți minimum 20 de caractere și marcați un punct în zona Bălți. Așteptați încărcarea pozelor. Limita este ${PILOT_JOB_LIMIT} cereri noi în 24 de ore. Dacă răspunsul se pierde, retrimiteți din același formular. Dacă datele sunt deja publicate, deschideți linkul afișat.` },
    { q: 'Cum primesc o copie a datelor sau șterg contul?', a: 'Scrieți la @kentukaa cu solicitarea și linkul profilului. Suportul trebuie să confirme titularul contului; nu trimiteți codul SMS sau pașaportul. Ștergerea automată din cont nu este încă disponibilă.' },
  ];
}
